version: '2'
services:
  fastapi:
    build: ./
    image: fastapi:v0.1.0
    container_name:
      fastapi
    ports:
      - "8321:80"
    env_file: app/.env
    environment:
      - WORKERS_PER_CORE=0.5           #worker_processes = WORKERS_PER_CORE*CPU cores
      - APP_MODULE=main:app
      - LOG_LEVEL=info
      - LOG_PATH=/var/log          #日志目录
      - RUN_ENV=dev                     # dev:开发环境; pro:生产环境;
    volumes:
      - ./app:/app
      - ./logs:/var/log

